import '../styles/globals.css'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ 
  weight: ['500'],
  subsets: ['latin']
 })

export const metadata = {
  title: 'Qui a la plus grosse ?',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}